import { PublicationWithRelations } from "./types";
import { SEED_RESEARCH_AREAS } from "../projects/seed-data";

export const SEED_PUBLICATIONS: PublicationWithRelations[] = [
  {
    id: "pub-1",
    title: "Microplastic ingestion and trophic transfer in commercially important teleosts of the Meghna River Estuary",
    slug: "microplastic-ingestion-trophic-transfer-meghna-estuary",
    abstract:
      "Microplastic pollution represents an escalating ecological concern across Southeast Asian estuarine networks. In this investigation, we quantified particle abundance, polymer composition via micro-FTIR imaging, and tissue translocation in 420 specimens across four trophic guilds. Polyethylene and polypropylene fibers dominated gastrointestinal and hepatic loads (mean 5.8 ± 1.2 particles/individual). Trophic magnification factors revealed significant bioaccumulation pathways, with predatory species demonstrating pronounced hepatic oxidative stress biomarker induction.",
    publication_type: "journal_article",
    journal: "Environmental Science & Technology",
    volume: "58",
    issue: "4",
    pages: "1892–1904",
    publication_year: 2026,
    publication_date: "2026-02-15",
    doi: "10.1021/acs.est.2026.04891",
    doi_url: "https://doi.org/10.1021/acs.est.2026.04891",
    pdf_url: "https://doi.org/10.1021/acs.est.2026.04891",
    external_url: "https://pubs.acs.org/journal/esthag",
    impact_factor: 11.4,
    citation_count: 38,
    quartile: "Q1",
    is_featured: true,
    is_published: true,
    display_order: 1,
    authors_text: "Nakayama, K., Vance, E., Rahman, M. A., & Chowdhury, S.",
    bibtex: `@article{nakayama2026microplastic,
  title={Microplastic ingestion and trophic transfer in commercially important teleosts of the Meghna River Estuary},
  author={Nakayama, Kotoha and Vance, Elena and Rahman, M. A. and Chowdhury, Sojib},
  journal={Environmental Science & Technology},
  volume={58},
  number={4},
  pages={1892--1904},
  year={2026},
  publisher={American Chemical Society},
  doi={10.1021/acs.est.2026.04891}
}`,
    created_at: "2026-02-15T00:00:00Z",
    updated_at: "2026-02-15T00:00:00Z",
    authors: [
      { name: "Kotoha Nakayama", is_lab_member: true, is_corresponding: true, display_order: 1 },
      { name: "Dr. Elena Vance", is_lab_member: true, is_corresponding: false, display_order: 2 },
      { name: "Sojib Chowdhury", is_lab_member: true, is_corresponding: false, display_order: 3 },
      { name: "M. A. Rahman", is_lab_member: false, is_corresponding: false, display_order: 4 },
    ],
    research_areas: [
      { id: "area-1", title: "Microplastics & Emerging Pollutants", slug: "microplastics-emerging-pollutants", icon_name: "FlaskConical" },
      { id: "area-3", title: "Aquatic Health & Watersheds", slug: "aquatic-health-watersheds", icon_name: "Droplets" },
    ],
    projects: [
      { id: "proj-1", title: "Microplastic Trophic Transfer & Nanoparticle Ecotoxicology in Estuarine Food Webs", slug: "microplastic-trophic-transfer-estuarine-food-webs", status: "ongoing" },
    ],
  },
  {
    id: "pub-2",
    title: "Heavy metal bioaccumulation and human health risk assessment in freshwater aquaculture systems of Bangladesh",
    slug: "heavy-metal-bioaccumulation-freshwater-aquaculture-bangladesh",
    abstract:
      "Aquaculture constitutes a critical protein source; however, uncontrolled industrial discharge introduces toxic non-essential trace elements into commercial ponds. We collected water, sediment, and fish tissues (Oreochromis niloticus, Pangasius hypophthalmus) across 18 major farming hubs to evaluate Cr, Cd, Pb, As, and Ni concentrations. Target Hazard Quotients (THQ) for inorganic arsenic and lead exceeded safe thresholds in 28% of adult consumption scenarios, underscoring urgent monitoring mandates for commercial feed supplies.",
    publication_type: "journal_article",
    journal: "Journal of Hazardous Materials",
    volume: "462",
    issue: "1",
    pages: "132890",
    publication_year: 2025,
    publication_date: "2025-11-20",
    doi: "10.1016/j.jhazmat.2025.132890",
    doi_url: "https://doi.org/10.1016/j.jhazmat.2025.132890",
    pdf_url: "https://doi.org/10.1016/j.jhazmat.2025.132890",
    external_url: "https://www.sciencedirect.com/journal/journal-of-hazardous-materials",
    impact_factor: 13.6,
    citation_count: 84,
    quartile: "Q1",
    is_featured: true,
    is_published: true,
    display_order: 2,
    authors_text: "Sultana, R., Kabir, M. S., & Islam, M. S.",
    bibtex: `@article{sultana2025heavy,
  title={Heavy metal bioaccumulation and human health risk assessment in freshwater aquaculture systems of Bangladesh},
  author={Sultana, R. and Kabir, M. S. and Islam, M. S.},
  journal={Journal of Hazardous Materials},
  volume={462},
  pages={132890},
  year={2025},
  publisher={Elsevier},
  doi={10.1016/j.jhazmat.2025.132890}
}`,
    created_at: "2025-11-20T00:00:00Z",
    updated_at: "2025-11-20T00:00:00Z",
    authors: [
      { name: "Sojib Chowdhury", is_lab_member: true, is_corresponding: true, display_order: 1 },
      { name: "Dr. Marcus Thorne", is_lab_member: true, is_corresponding: false, display_order: 2 },
      { name: "M. S. Islam", is_lab_member: false, is_corresponding: false, display_order: 3 },
    ],
    research_areas: [
      { id: "area-2", title: "Heavy Metal Ecotoxicology", slug: "heavy-metal-ecotoxicology", icon_name: "Atom" },
      { id: "area-4", title: "Human Health Risk Assessment", slug: "human-health-risk-assessment", icon_name: "Activity" },
    ],
    projects: [
      { id: "proj-2", title: "Biogeochemical Speciation & Chronic Human Health Risk of Heavy Metals in Peri-Urban Aquifers", slug: "biogeochemical-speciation-heavy-metals-aquifers", status: "ongoing" },
    ],
  },
  {
    id: "pub-3",
    title: "Organophosphate and neonicotinoid pesticide residues in intensive agricultural catchments: Seasonal dynamics and ecological hazard quotients",
    slug: "pesticide-residues-intensive-agricultural-catchments",
    abstract:
      "Intensive crop production in the Bengal delta relies on complex agrochemical mixtures. Using liquid chromatography-tandem mass spectrometry (LC-MS/MS), we monitored 24 parent pesticide compounds and primary transformation metabolites across monsoon, post-monsoon, and dry seasons. Chlorpyrifos and imidacloprid concentrations frequently peaked following early monsoon flush events, surpassing European freshwater protective thresholds for benthic invertebrates.",
    publication_type: "journal_article",
    journal: "Science of The Total Environment",
    volume: "895",
    issue: "3",
    pages: "167234",
    publication_year: 2025,
    publication_date: "2025-08-10",
    doi: "10.1016/j.scitotenv.2025.167234",
    doi_url: "https://doi.org/10.1016/j.scitotenv.2025.167234",
    pdf_url: "https://doi.org/10.1016/j.scitotenv.2025.167234",
    external_url: "https://www.sciencedirect.com/journal/science-of-the-total-environment",
    impact_factor: 9.8,
    citation_count: 52,
    quartile: "Q1",
    is_featured: true,
    is_published: true,
    display_order: 3,
    authors_text: "Ahmed, T., Kabir, M. S., & Chowdhury, M. A.",
    bibtex: `@article{ahmed2025organophosphate,
  title={Organophosphate and neonicotinoid pesticide residues in intensive agricultural catchments: Seasonal dynamics and ecological hazard quotients},
  author={Ahmed, T. and Kabir, M. S. and Chowdhury, M. A.},
  journal={Science of The Total Environment},
  volume={895},
  pages={167234},
  year={2025},
  publisher={Elsevier},
  doi={10.1016/j.scitotenv.2025.167234}
}`,
    created_at: "2025-08-10T00:00:00Z",
    updated_at: "2025-08-10T00:00:00Z",
    authors: [
      { name: "Dr. Elena Vance", is_lab_member: true, is_corresponding: true, display_order: 1 },
      { name: "Aria Lindqvist", is_lab_member: true, is_corresponding: false, display_order: 2 },
      { name: "T. Ahmed", is_lab_member: false, is_corresponding: false, display_order: 3 },
    ],
    research_areas: [
      { id: "area-3", title: "Aquatic Health & Watersheds", slug: "aquatic-health-watersheds", icon_name: "Droplets" },
      { id: "area-4", title: "Human Health Risk Assessment", slug: "human-health-risk-assessment", icon_name: "Activity" },
    ],
    projects: [
      { id: "proj-3", title: "Longitudinal River Basin Biomonitoring & Industrial Effluent Impact Assessment", slug: "longitudinal-river-basin-biomonitoring", status: "completed" },
    ],
  },
  {
    id: "pub-4",
    title: "Engineered magnetic biochar nanocomposites for high-efficiency sequestration of hexavalent chromium from industrial tanneries",
    slug: "magnetic-biochar-nanocomposites-chromium-sequestration",
    abstract:
      "Tannery effluent remediation demands low-cost, scalable adsorbents capable of rapid Cr(VI) reduction and immobilization. Here, we synthesized magnetic Fe3O4-functionalized rice husk biochar via one-step pyrolysis. Batch adsorption experiments exhibited maximum Langmuir adsorption capacity of 142.6 mg/g at pH 2.0. XPS and FTIR analyses confirmed a coupled reduction-complexation mechanism where Cr(VI) was reduced to less toxic Cr(III) on surface functional groups with 99.2% magnetic recovery.",
    publication_type: "journal_article",
    journal: "Chemosphere",
    volume: "338",
    issue: "2",
    pages: "139420",
    publication_year: 2024,
    publication_date: "2024-10-05",
    doi: "10.1016/j.chemosphere.2024.139420",
    doi_url: "https://doi.org/10.1016/j.chemosphere.2024.139420",
    pdf_url: "https://doi.org/10.1016/j.chemosphere.2024.139420",
    external_url: "https://www.sciencedirect.com/journal/chemosphere",
    impact_factor: 8.94,
    citation_count: 116,
    quartile: "Q1",
    is_featured: true,
    is_published: true,
    display_order: 4,
    authors_text: "Chowdhury, S., Vance, E., Thorne, M., & Alam, M. N.",
    bibtex: `@article{chowdhury2024magnetic,
  title={Engineered magnetic biochar nanocomposites for high-efficiency sequestration of hexavalent chromium from industrial tanneries},
  author={Chowdhury, S. and Vance, E. and Thorne, M. and Alam, M. N.},
  journal={Chemosphere},
  volume={338},
  pages={139420},
  year={2024},
  publisher={Elsevier},
  doi={10.1016/j.chemosphere.2024.139420}
}`,
    created_at: "2024-10-05T00:00:00Z",
    updated_at: "2024-10-05T00:00:00Z",
    authors: [
      { name: "Sojib Chowdhury", is_lab_member: true, is_corresponding: true, display_order: 1 },
      { name: "Dr. Elena Vance", is_lab_member: true, is_corresponding: false, display_order: 2 },
      { name: "Dr. Marcus Thorne", is_lab_member: true, is_corresponding: false, display_order: 3 },
    ],
    research_areas: [
      { id: "area-5", title: "Environmental Remediation Technologies", slug: "environmental-remediation-technologies", icon_name: "Leaf" },
      { id: "area-2", title: "Heavy Metal Ecotoxicology", slug: "heavy-metal-ecotoxicology", icon_name: "Atom" },
    ],
    projects: [
      { id: "proj-4", title: "Engineered Biochar & Phytoremediation Matrices for Textile & Tannery Effluent Cleanup", slug: "engineered-biochar-phytoremediation-effluent-cleanup", status: "completed" },
    ],
  },
  {
    id: "pub-5",
    title: "Sub-lethal neurotoxicity and oxidative stress in zebrafish (Danio rerio) larvae exposed to combined textile dye and nanoplastic mixtures",
    slug: "sublethal-neurotoxicity-zebrafish-dye-nanoplastic",
    abstract:
      "Real-world aquatic ecosystems encounter complex chemical-particulate mixtures. We assessed the joint toxicity of azo dye Reactive Red 120 and 50 nm polystyrene nanoplastics on embryonic zebrafish development. Co-exposure elicited synergistic increases in reactive oxygen species (ROS) generation, acetylcholinesterase (AChE) inhibition, and behavioral hypoactivity during alternating light-dark photoperiod challenges.",
    publication_type: "journal_article",
    journal: "Aquatic Toxicology",
    volume: "264",
    issue: "1",
    pages: "106720",
    publication_year: 2024,
    publication_date: "2024-04-18",
    doi: "10.1016/j.aquatox.2024.106720",
    doi_url: "https://doi.org/10.1016/j.aquatox.2024.106720",
    pdf_url: "https://doi.org/10.1016/j.aquatox.2024.106720",
    external_url: "https://www.sciencedirect.com/journal/aquatic-toxicology",
    impact_factor: 5.2,
    citation_count: 67,
    quartile: "Q1",
    is_featured: false,
    is_published: true,
    display_order: 5,
    authors_text: "Nakayama, K., Vance, E., Lindqvist, A., & Chowdhury, S.",
    bibtex: `@article{nakayama2024sublethal,
  title={Sub-lethal neurotoxicity and oxidative stress in zebrafish (Danio rerio) larvae exposed to combined textile dye and nanoplastic mixtures},
  author={Nakayama, Kotoha and Vance, Elena and Lindqvist, Aria and Chowdhury, Sojib},
  journal={Aquatic Toxicology},
  volume={264},
  pages={106720},
  year={2024},
  publisher={Elsevier},
  doi={10.1016/j.aquatox.2024.106720}
}`,
    created_at: "2024-04-18T00:00:00Z",
    updated_at: "2024-04-18T00:00:00Z",
    authors: [
      { name: "Kotoha Nakayama", is_lab_member: true, is_corresponding: true, display_order: 1 },
      { name: "Dr. Elena Vance", is_lab_member: true, is_corresponding: false, display_order: 2 },
      { name: "Aria Lindqvist", is_lab_member: true, is_corresponding: false, display_order: 3 },
      { name: "Sojib Chowdhury", is_lab_member: true, is_corresponding: false, display_order: 4 },
    ],
    research_areas: [
      { id: "area-1", title: "Microplastics & Emerging Pollutants", slug: "microplastics-emerging-pollutants", icon_name: "FlaskConical" },
      { id: "area-2", title: "Heavy Metal Ecotoxicology", slug: "heavy-metal-ecotoxicology", icon_name: "Atom" },
    ],
    projects: [
      { id: "proj-1", title: "Microplastic Trophic Transfer & Nanoparticle Ecotoxicology in Estuarine Food Webs", slug: "microplastic-trophic-transfer-estuarine-food-webs", status: "ongoing" },
    ],
  },
  {
    id: "pub-6",
    title: "Global occurrence, ecotoxicity, and remediation technologies of poly- and perfluoroalkyl substances (PFAS) in aquatic environments: A critical review",
    slug: "global-occurrence-ecotoxicity-remediation-pfas-review",
    abstract:
      "Per- and polyfluoroalkyl substances (PFAS) represent highly persistent anthropogenic synthetic chemicals of global environmental concern. This critical review consolidates recent advances in high-resolution analytical detection, environmental partitioning kinetics across aquatic biomes, multi-generational ecotoxicological endpoints, and destructive remediation methodologies including plasma oxidation, subcritical water hydrolysis, and electrochemical mineralization.",
    publication_type: "review",
    journal: "Water Research",
    volume: "242",
    issue: "Pt A",
    pages: "120340",
    publication_year: 2023,
    publication_date: "2023-09-01",
    doi: "10.1016/j.watres.2023.120340",
    doi_url: "https://doi.org/10.1016/j.watres.2023.120340",
    pdf_url: "https://doi.org/10.1016/j.watres.2023.120340",
    external_url: "https://www.sciencedirect.com/journal/water-research",
    impact_factor: 12.8,
    citation_count: 198,
    quartile: "Q1",
    is_featured: true,
    is_published: true,
    display_order: 6,
    authors_text: "Thorne, M., Vance, E., Zhang, Y., & Miller, J. K.",
    bibtex: `@article{thorne2023global,
  title={Global occurrence, ecotoxicity, and remediation technologies of poly- and perfluoroalkyl substances (PFAS) in aquatic environments: A critical review},
  author={Thorne, M. and Vance, E. and Zhang, Y. and Miller, J. K.},
  journal={Water Research},
  volume={242},
  pages={120340},
  year={2023},
  publisher={Elsevier},
  doi={10.1016/j.watres.2023.120340}
}`,
    created_at: "2023-09-01T00:00:00Z",
    updated_at: "2023-09-01T00:00:00Z",
    authors: [
      { name: "Dr. Marcus Thorne", is_lab_member: true, is_corresponding: true, display_order: 1 },
      { name: "Dr. Elena Vance", is_lab_member: true, is_corresponding: false, display_order: 2 },
    ],
    research_areas: [
      { id: "area-1", title: "Microplastics & Emerging Pollutants", slug: "microplastics-emerging-pollutants", icon_name: "FlaskConical" },
      { id: "area-5", title: "Environmental Remediation Technologies", slug: "environmental-remediation-technologies", icon_name: "Leaf" },
    ],
    projects: [
      { id: "proj-1", title: "Microplastic Trophic Transfer & Nanoparticle Ecotoxicology in Estuarine Food Webs", slug: "microplastic-trophic-transfer-estuarine-food-webs", status: "ongoing" },
    ],
  },
  {
    id: "pub-7",
    title: "Spatial distribution and health hazard indices of groundwater arsenic in alluvial aquifers of the Central Meghna floodplain",
    slug: "spatial-distribution-hazard-groundwater-arsenic-meghna",
    abstract:
      "Hydrogeological sampling of 280 tubewells across four depth intervals in the Central Meghna floodplain revealed extensive arsenic enrichment (>50 µg/L) in Holocene shallow sand aquifers (15–45 m). Multivariate geostatistical kriging and principal component analysis indicated microbially mediated reductive dissolution of iron oxyhydroxides as the dominant mobilization mechanism, affecting approximately 64,000 residents in vulnerable sub-districts.",
    publication_type: "journal_article",
    journal: "Environmental Pollution",
    volume: "312",
    issue: "1",
    pages: "120011",
    publication_year: 2022,
    publication_date: "2022-11-15",
    doi: "10.1016/j.envpol.2022.120011",
    doi_url: "https://doi.org/10.1016/j.envpol.2022.120011",
    pdf_url: "https://doi.org/10.1016/j.envpol.2022.120011",
    external_url: "https://www.sciencedirect.com/journal/environmental-pollution",
    impact_factor: 8.9,
    citation_count: 142,
    quartile: "Q1",
    is_featured: false,
    is_published: true,
    display_order: 7,
    authors_text: "Chowdhury, S., Vance, E., & Rahman, M. M.",
    bibtex: `@article{chowdhury2022spatial,
  title={Spatial distribution and health hazard indices of groundwater arsenic in alluvial aquifers of the Central Meghna floodplain},
  author={Chowdhury, S. and Vance, E. and Rahman, M. M.},
  journal={Environmental Pollution},
  volume={312},
  pages={120011},
  year={2022},
  publisher={Elsevier},
  doi={10.1016/j.envpol.2022.120011}
}`,
    created_at: "2022-11-15T00:00:00Z",
    updated_at: "2022-11-15T00:00:00Z",
    authors: [
      { name: "Sojib Chowdhury", is_lab_member: true, is_corresponding: true, display_order: 1 },
      { name: "Dr. Elena Vance", is_lab_member: true, is_corresponding: false, display_order: 2 },
    ],
    research_areas: [
      { id: "area-2", title: "Heavy Metal Ecotoxicology", slug: "heavy-metal-ecotoxicology", icon_name: "Atom" },
      { id: "area-4", title: "Human Health Risk Assessment", slug: "human-health-risk-assessment", icon_name: "Activity" },
    ],
    projects: [
      { id: "proj-2", title: "Biogeochemical Speciation & Chronic Human Health Risk of Heavy Metals in Peri-Urban Aquifers", slug: "biogeochemical-speciation-heavy-metals-aquifers", status: "ongoing" },
    ],
  },
  {
    id: "pub-8",
    title: "Seasonal variations and flux estimation of plastic debris discharge into the Northern Bay of Bengal from coastal river networks",
    slug: "plastic-debris-discharge-northern-bay-of-bengal",
    abstract:
      "We deployed visual counting, surface net trawls, and drone-assisted aerial photogrammetry across five estuarine outlets to quantify macro- and mesoplastic mass fluxes into the Northern Bay of Bengal. Seasonal monsoon discharge escalated plastic export by 3.8-fold compared to dry periods, with high-density polyethylenes and single-use packaging accounting for 72% of total plastic mass.",
    publication_type: "conference_paper",
    journal: "Proceedings of the International Coastal & Estuarine Research Federation",
    volume: "14",
    issue: "2",
    pages: "45–56",
    publication_year: 2022,
    publication_date: "2022-05-20",
    doi: "10.1007/978-3-030-94210-4_5",
    doi_url: "https://doi.org/10.1007/978-3-030-94210-4_5",
    pdf_url: "https://doi.org/10.1007/978-3-030-94210-4_5",
    external_url: "https://link.springer.com",
    impact_factor: 3.8,
    citation_count: 29,
    quartile: "Q2",
    is_featured: false,
    is_published: true,
    display_order: 8,
    authors_text: "Lindqvist, A., Vance, E., & Chowdhury, S.",
    bibtex: `@inproceedings{lindqvist2022seasonal,
  title={Seasonal variations and flux estimation of plastic debris discharge into the Northern Bay of Bengal from coastal river networks},
  author={Lindqvist, A. and Vance, E. and Chowdhury, S.},
  booktitle={Proceedings of the International Coastal & Estuarine Research Federation},
  pages={45--56},
  year={2022},
  publisher={Springer}
}`,
    created_at: "2022-05-20T00:00:00Z",
    updated_at: "2022-05-20T00:00:00Z",
    authors: [
      { name: "Aria Lindqvist", is_lab_member: true, is_corresponding: true, display_order: 1 },
      { name: "Dr. Elena Vance", is_lab_member: true, is_corresponding: false, display_order: 2 },
      { name: "Sojib Chowdhury", is_lab_member: true, is_corresponding: false, display_order: 3 },
    ],
    research_areas: [
      { id: "area-1", title: "Microplastics & Emerging Pollutants", slug: "microplastics-emerging-pollutants", icon_name: "FlaskConical" },
      { id: "area-3", title: "Aquatic Health & Watersheds", slug: "aquatic-health-watersheds", icon_name: "Droplets" },
    ],
    projects: [
      { id: "proj-1", title: "Microplastic Trophic Transfer & Nanoparticle Ecotoxicology in Estuarine Food Webs", slug: "microplastic-trophic-transfer-estuarine-food-webs", status: "ongoing" },
    ],
  },
];
